name = "SFilters"
uuid = "cc5fff61-e9d2-4954-93e3-780cb2579f4b"
authors = ["Naoki Maeda <fnkyksj@gmail.com> and contributors"]
version = "0.1.1-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
