name = "SFilters"
uuid = "cc5fff61-e9d2-4954-93e3-780cb2579f4b"
version = "0.2.0-DEV"
authors = ["Naoki Maeda <fnkyksj@gmail.com> and contributors"]

[deps]
RdWaveFiles = "46bd9b67-29e2-46b0-bb29-da07b42f7d11"

[compat]
RdWaveFiles = "0.3.3"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
